name: ChatApp Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v4

    - name: Setup Node.js Environment
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Validate Backend Assets
      run: |
        cd backend
        npm install

    - name: Validate Frontend Assets
      run: |
        cd frontend
        rm -rf node_modules package-lock.json
        npm install
        npm run build
